from src.exception import CustomException
from src.logger import logging
from src.dependencies import sys,time,TICKET_CREATION_OPENAI_ASSIRANT_ID
from src.instances import openAI_client
from src.workers.tickets.instances import ticket_creation_thread

def create_ticket_response(conversation):
    """ 
    Function to generate a ticket response run from a given conversation. The primary aim would be to push
    a conversation to the ticket thread and run the thread for the assistant to generate a ticket

    Args:
        conversation (list): An list of  JSON parsable string object of string key value pairs, where each key is the sender and each value is their message 
        from them.

    Returns:
        run : The run object from OpenAI Assistants (https://platform.openai.com/docs/api-reference/runs/object)
    """
    try:
        openAI_client.beta.threads.messages.create(
            thread_id=ticket_creation_thread.id,
            role="user",
            content= [{
                "type" : "text",
                "text" : str(conversation)
            }]
        )
                
        run = openAI_client.beta.threads.runs.create(
            thread_id=ticket_creation_thread.id,
            assistant_id=TICKET_CREATION_OPENAI_ASSIRANT_ID,
        )
        
        return run
        
    except Exception as e:
        raise CustomException(e,sys)

def get_ticket(thread, run):
    """ 
    Function to get the ticket generated by the assistant in the thread and run provided.

    Args:
        1. thread : The thread object from OpenAI Assistants (https://platform.openai.com/docs/api-reference/threads/object)
        2. run : The run object from OpenAI Assistants (https://platform.openai.com/docs/api-reference/runs/object)

    Returns:
        messages : The messages object from OpenAI Assistants (https://platform.openai.com/docs/api-reference/messages/object)
    """
    try:
        while True:
            run = openAI_client.beta.threads.runs.retrieve(
                thread_id=thread.id,
                run_id=run.id
            )
            if run.status == 'completed':
                messages = openAI_client.beta.threads.messages.list(
                    thread_id=thread.id
                )
                return messages
            elif run.status in ['failed', 'cancelled', 'expired']:
                raise Exception(f"Run ended with status: {run.status}")
            time.sleep(1)
    except Exception as e:
        raise CustomException(e,sys)
    
    
async def new_ticket(conversation,thread_id):
    """
        Function to get the Q&A pair generated given the conversation and prepare it as a dictionary, with conversation ID as the key (dummy id generated using uuid for now).
        
        Args:
            conversation : A dictionary containing the conversation between the user and the assistant
            
        Returns:
            QA : A dictionary containing the Q&A pair generated by the assistant
    """
    try : 
        run = create_ticket_response(conversation)
        messages = get_ticket(ticket_creation_thread, run)
        
        ticket = {}
        
        if(messages):
            ticket['status'] = 200
            ticket['thread_id'] = thread_id
            ticket['content'] = messages.data[0].content[0].text.value
            
        else:
            ticket['status'] = 404
            ticket['thread_id'] = thread_id
            ticket['content'] = "The assistant was unable to generate a ticket for the given conversation."
            
            
        return ticket
    except Exception as e:
        raise CustomException(e,sys)